### ISSUE TITLE
Dokumentacja - do przegadania z kierownikiem

### ISSUE THREAD

**Issue by Polkasa** [TajneStudio/KwadrateX#12]
Patryku! Musimy przegadać sprawy związane z dokumentacją do 5 maja 2015! Zgłoś się do mnie jak najszybciej!

**Comment by Telusp** [comment]
Daniel?

**Comment by Polkasa** [comment]
Już poprawiłem, sorki :dancers:

**Comment by Polkasa** [comment]
Przypominam o upływającym terminie realizacji issue!

**Comment by Polkasa** [comment]
Przegadano i issue zamykam
