### ISSUE TITLE
Dokumentacja - Domykanie

### ISSUE THREAD

**Issue by Polkasa** [TajneStudio/KwadrateX#15]
Musimy powoli domykać dokumentację. Czego nam potrzeba? Możesz mi wypisać tutaj dokładnie?

**Comment by Telusp** [comment]
Potrzeba wyciągnąć komentarze dokumentacyjne z kodu, diagram klas, logo firmy i gry, screeny strony i hormonogram. Wydaje mi się, że to wszystko by dokumentacja była odpowiednio zrobiona.
