### ISSUE TITLE
Grafika czapek

### ISSUE THREAD

**Issue by Polkasa** [TajneStudio/KwadrateX#9]
Pawle! Zrób grafiki co najmniej 20 czapek do 5 maja 2015!

**Comment by Polkasa** [comment]
Przypominam o upływającym terminie realizacji issue!

**Comment by pawelbiezunski** [comment]
Wrzzuciłem "grafiki" na githuba. Proszę się nie śmiać z jakości wykonania,
do jasnej ciasnej nie jestem grafikiem hjahahha:p

2015-05-04 10:06 GMT+02:00 Łukasz <notifications@github.com>:
